artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://github.com/sanketbabar2001/careers_website/blob/main/summarizer-data.zip
  local_data_file: data/data.zip
  unzip_dir: artifacts/data_ingestion



